config/routes.rb
Rails.application.routes.draw do
  root to: 'conversations#new'

  resources :conversations, only: [:create, :new, :show]
  resources :users, only: [:show, :update]
  # Serve websocket cable requests in-process
   mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :starter, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  has_many :messages
  has_secure_token

  validates_length_of :pin, :minimum => 5, :maximum => 5

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
  helper_method :current_user, :channel
  before_action :set_locale

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session


  private
  def set_locale
    cookies[:locale] = params[:locale] if params[:locale].present?
    I18n.locale = params[:locale] || cookies[:locale] ||I18n.default_locale
  end
  def current_user
    @current_user ||= User.find_by_id(session[:key])
  end
  def channel
    @channel ||= cookies[:channel]
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def create
    if session[:key].nil?
      @user = User.create!
      session[:key] = @user.id
    else
      @user = User.find session[:key]
    end
    @conversation = Conversation.new(starter:@user, pin:params[:conversation][:pin])
    if @conversation.save
      cookies[:channel] = @conversation.token
      respond_with @conversation, location: conversation_path(@conversation, :token => @conversation.token, :user => @user.token)
    else
      respond_with @conversation
    end
  end
  def new
    @locale = cookies['locale'].nil?
    @conversation = Conversation.new
    respond_with @conversation
  end
  def show
    @conversation = Conversation.includes(:messages).find_by(id:params[:id], token:params[:token])
    @popup = true
    @user = nil
    if @conversation.nil?
      redirect_to root_path and return
    end
    if @conversation.receiver.present?
      redirect_to root_path and return
    end

    if params[:user].nil? and session[:key].nil?
      @user = User.create!
      session[:key]=@user.id
      redirect_to user_path(@user, token: @conversation.token) and return
    elsif session[:key].present? and params[:user].nil?
      @user = User.find session[:key]
      redirect_to user_path(@user, token: @conversation.token) and return
    elsif session[:key].present?
      @user = User.find session[:key]
    elsif params[:user].nil?
      redirect_to root_path and return
    end

    if @conversation.receiver.nil? and @user.id != @conversation.starter_id
      @conversation.update_attributes(receiver: @user)
      cookies[:channel] = @conversation.token
      @popup = false
    end
    respond_with @conversation
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @conversation = Conversation.find_by token: params[:token]
    @user = User.find params[:id]
  end
  def update
    @conversation = Conversation.find_by token: params[:conversation]
    if @conversation.pin.eql? params[:pin]
      @user = User.find params[:id]
      session[:key] = @user.id
      redirect_to conversation_path(@conversation, :token => @conversation.token, :user => @user.token)
    else
      redirect_to user_path( @user, token: @conversation.token)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/new.html.erb
<div class="jumbotron">
  <h1 class="text-center">P-Chat</h1>
  <p class="text-center">
    <%= t '.title' %>
  </p>
  <%= simple_form_for @conversation do |f| %>
      <div class="text-center"><%= t '.pin' %></div>
      <div style="width: 200px;" class="center-block form-group">
        <input style="font-size: x-large" class="string optional form-control" maxlength="5" type="password" name="conversation[pin]" id="conversation_pin">
      </div>
      <%= f.button :submit, class: 'center-block btn btn-primary btn-lg' %>
  <% end %>
  <br>
    <p class="text-center">
      <%= t '.info' %>
    </p>
  </br>

  <div class="modal fade" id="locale" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">
            <%= t '.dialog.title' %>
          </h4>
        </div>
        <div class="modal-body">
          <p class="text-center">
            <%= t '.dialog.body' %>
          </p>
          <div class="text-center">
            <div aria-label="..." class="btn-group" role="group">
              <a href="/?locale=de">
                <button class="btn btn-default btn-lg" type="button">Deutsch</button>
              </a>
              <a href="/?locale=en">
                <button class="btn btn-default btn-lg" type="button">English</button>
              </a>
              <a href="/?locale=tr">
                <button class="btn btn-default btn-lg" type="button">Türkçe</button>
              </a>
            </div>
          </div>
          <br/>
          <div class="modal-footer">
            <button class="btn btn-default" data-dismiss="modal" type="button">
              <%= t '.dialog.close' %>
            </button>
          </div>
        </div>
      </div>
    </div>
    <button class="hidden" data-target="#locale" data-toggle="modal" id="open-model" type="button"></button>
    <% if @locale %>
        <script !src="">
          $(document).ready(function() {
            $('#open-model').click();
          });
        </script>
    <% end %>
  </div>
</div>

app/views/conversations/show.html.erb
<h1 class="text-center">
  <%= t '.title' %>
</h1>
<input id="user" type="hidden" value="<%=session[:key] %>">
<input id="conversation" type="hidden" value="<%= @conversation.id %>">

<div class="jumbotron">
  <div class="input-group">
    <input class="form-control" placeholder="<%= t '.placeholder' %>" id="input-send" type="text">
    <span class="input-group-btn">
      <button class="btn btn-default" id="send" type="button">
        <%= t '.send' %>
      </button>
    </span>
  </div>

  <br>
    <br>
      <div id="messages">
        <%= render @conversation.messages %>
      </div>
    </br>
  <div class="modal fade" id="info" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">
              <%= t '.dialog.title' %>
            </h4>
          </div>
          <div class="modal-body">
            <p>
              <%= t '.dialog.body' %>
            </p>
            <input class="form-control" id="fe_text" type="text" value="<%= conversation_url(@conversation, token: @conversation.token) %>" aria-describedby="basic-addon2">
            <br/>
            <div class="modal-footer">
              <button class="btn btn-default" data-dismiss="modal" type="button">
                <%= t '.dialog.close' %>
              </button>
            </div>
          </div>
        </div>
      </div>
      <button class="hidden" data-target="#info" data-toggle="modal" id="open-model" type="button"></button>
      <% if @popup %>
          <script !src="">
            $(document).ready(function() {
             $('#open-model').click();
            });
          </script>
      <% end %>
    </div>

</div>

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'P-Chat', root_path, class: 'navbar-brand'
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if params['controller'] == 'conversations' and params['action'] == 'new'
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = t 'layouts.language'
              %span.caret
            %ul.dropdown-menu
              %li
                %a{:href => "#{root_url}?locale=de"} Deutsch
              %li
                %a{:href => "#{root_url}?locale=en"} English
              %li
                %a{:href => "#{root_url}?locale=tr"} Türkçe
    / /.nav-collapse

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PChat
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %body
    = render 'layouts/navbar'
    .container
      = yield

app/views/messages/_message.html.haml
- cache message do
  .panel.panel-default
    .panel-heading
      = t 'messages.title'
      _#{message.user.token.first(6).downcase}
    .panel-body
      = message.content

app/views/users/show.html.erb
<div class="jumbotron">
  <h1 class="text-center">P-Chat</h1>
  <p class="text-center">
    <%= t '.title' %>
  </p>
  <%= simple_form_for @user do |f| %>
      <input id="conversation" type="hidden" name="conversation" value="<%= @conversation.token %>">
      <div class="text-center"><%= t '.pin' %></div>
      <div style="width: 200px;" class="center-block form-group">
        <input style="font-size: x-large" class="string optional form-control" maxlength="5" type="password" name="pin" id="conversation_pin">
      </div>
      <input type="submit" name="commit" value="&nbsp;&nbsp;&nbsp;Ok&nbsp;&nbsp;&nbsp;" class="btn btn-default center-block btn btn-primary btn-lg" data-disable-with="Update User">
  <% end %>
  <br>

</div>